import { Router } from "express";
import { createusuario, dataCorreos, login, setDatosUsuario, updateusuario,getusuario} from "../controllers/task.controllers.js"
import { getCliente, updateCliente, getClientsbyDNI, getAllClientes, getAlldistritos,getAllregion,getAlleducativo,getAllestado,getAllmotivo, deleteCliente, deleteClientes, createcliente, getAllusuario, getDistrito, getRegion, getEstado, getEducativo, getMotivo, deleteAllClientes, getClientesbyNivelEducativo, getClientesbyMotivo, getClientesbyEstadoCivil, getClientesbyDistrito, getClientesbyRegion, getClientesbyMotivoDistrito, getClientesbyNivelEducativoDistrito, getClientesbyEstadoCivilDistrito, getClientesbyNivelEducativoRegion, getClientesbyMotivoRegion, getClientesbyEstadoCivilRegion, getDistritosbyRegion, getAllClientesbyRegion, getAllClientesbyDistrito} from "../controllers/cliente.controller.js"
const router=Router();

router.post('/registrousuario',createusuario)
router.post('/registrousuario1',login)
router.get('/distrito',getAlldistritos)
router.get('/distrito/:id',getDistrito)
router.get('/region',getAllregion)
router.get('/region/:id',getRegion)
router.get('/motivo',getAllmotivo)
router.get('/motivo/:id',getMotivo)
router.get('/estado',getAllestado)
router.get('/estado/:id',getEstado)
router.get('/educativo',getAlleducativo)
router.get('/educativo/:id',getEducativo)
router.get('/usuarios/:id',getusuario)
router.get('/usuario',getAllusuario)
router.put('/usuario',updateusuario)
router.post('/usuario2',setDatosUsuario)
router.post('/correo', dataCorreos)
router.post('/cliente',createcliente)
router.get('/clientes',getAllClientes)
router.get('/clients/:id',getClientsbyDNI)
router.get('/clientesporeducativo/:id',getClientesbyNivelEducativo)
router.get('/clientesporeducativodistrito/:id/:distrito',getClientesbyNivelEducativoDistrito)
router.get('/clientesporeducativoregion/:id/:region',getClientesbyNivelEducativoRegion)
router.get('/clientespormotivo/:id',getClientesbyMotivo)
router.get('/clientespormotivodistrito/:id/:distrito',getClientesbyMotivoDistrito)
router.get('/clientespormotivoregion/:id/:region',getClientesbyMotivoRegion)
router.get('/clientesporestadocivil/:id',getClientesbyEstadoCivil)
router.get('/clientesporestadocivildistrito/:id/:distrito',getClientesbyEstadoCivilDistrito)
router.get('/clientesporestadocivilregion/:id/:region',getClientesbyEstadoCivilRegion)
router.get('/clientespordistrito/:id',getClientesbyDistrito)
router.get('/allclientespordistrito/:id',getAllClientesbyDistrito)
router.get('/clientesporregion/:id',getClientesbyRegion)
router.get('/allclientesporregion/:id',getAllClientesbyRegion)
router.get('/distritosporregion/:id',getDistritosbyRegion)
router.get('/cliente/:id',getCliente)
router.put('/cliente/:id',updateCliente)
router.delete('/cliente/:id',deleteCliente)
router.delete('/clientes/:id',deleteClientes)
router.delete('/clientes',deleteAllClientes)
export default router;